baseURL = 'https://matar.oneß'
languageCode = 'en-us'
title = 'Matar Alhawiti'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Personal Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'eink'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
My name is **Matar**, I am a data engineer. I'm interested in distributed systems, cloud computing, data engineering, ML/AI and MLOps.

I love rock music 🎸, video games 🎮, movies 🎥.

You can reach me at: matar@linux.com
"""

# Collection to display on home
# homeCollectionTitle = 'Posts'
# homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/mataralhawiti/"

[[params.social]]
name = "github"
url = "https://github.com/mataralhawiti"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "music"
url = "/music"

[[params.menu]]
name = "movies"
url = "/movies"

[[params.menu]]
name = "vidoe games"
url = "/games"

# [[params.menu]]
# name = "about"
# url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
